aap/urls.py
from django.urls import path
from . import views

app_name = 'aap'

urlpatterns = [
    path("", views.home, name="home"),
    path("prod/", views.prod, name="prod"),
    path("expi/", views.tim, name="expi"),
    path("product_detail/", views.product_detail, name="product_detail"),
    path('expi/<int:id>/delete/', views.delet, name="delet"),
    path('<int:id>/update/', views.update, name="update"),
    path("expiring_products/", views.expiring_products, name="expiring_products"),
    path("expiring_soon/", views.expiring_soon, name="expiring_soon"),
    path("exp_60/", views.exp_60, name="exp_60"),
    path("product_search/", views.product_search, name="product_search"),
    path('orderby/', views.ordered, name="orderby"),
    path('order/', views.order, name="order"),
    path("bill/", views.bill, name="bill"),
    path("success/", views.success, name="success"),
    path('again/', views.search_jav, name='search'),
    path('again/newpage/', views.newpage, name='newpage'),
    path('nextpage/', views.nextpage, name='nextpage'),
    path('submit_form/', views.submit_form, name="bill"),
    path('add_medicine/', views.insertbysupplier, name="add_medicine"),

    path('bill/detail/<int:bill_id>/',views.bill_detail,name='bill_detail'),
    path('bill/create/',views.create_bill,name='bill_detail')

]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register-Merchant/', views.MerchantRegister, name="MerchantRegister"),
    path('signin/', views.signin, name="signin"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('signout/', views.signout, name="signout"),
    path('register-Supplier/',views.registerSupplier,name="SupplierRegister"),
    path('activate/<uidb64>/<token>/', views.activate,name="activate"),
    
]

first/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aap.urls')),
    path('accounts/',include('accounts.urls')),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager

# Create your models here.

# Create your models here.
class UserManager(BaseUserManager): #this only contain methods
    def create_user(self,first_name,last_name,username,email,password=None):
        if not email:
            raise ValueError("user must possess email")
        if not username:
            raise ValueError("user must have username")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,first_name,last_name,username,email,password=None):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser): #this only contain fields and calls methods
    Supplier = 1
    Merchant = 2

    ROLE_CHOICE = (
        (Supplier, 'Supplier'),
        (Merchant, 'Merchant'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    # required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Supplier'
        elif self.role == 2:
            user_role = 'Merchant'
        return user_role

accounts/forms.py
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password','confirm_password']
    
    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and Confirm Password does not match!"
            )

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from accounts.models import User
from django.contrib.auth.tokens import default_token_generator
from .models import User
from .utils import send_verification_email
from .forms import UserForm
from django.contrib import messages
from django.utils.http import urlsafe_base64_decode
from supplier.models import Supplier
from supplier.forms import SupplierForm
from django.template.defaultfilters import slugify
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from aap.models import products
from .utils import send_notification
from django.core.mail import send_mail
from datetime import date,timedelta,datetime
from django.utils import timezone

# Create your views here.
def MerchantRegister(request):
    if request.user.is_authenticated:
        # messages.warning(request,"You are already Logged in !")
        return redirect('accounts:dashboard')
    
    
    elif request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username'] 
            password = form.cleaned_data['password']
            user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email,password=password)
            user.role = User.Merchant
            user.set_password(password)
            user.save()
            print(user.id)
            #verification
            
            #send verification mail
            mail_subject = 'Please activate your account'
            mail_template = 'accounts/emails/account_verification_email.html'
            send_verification_email(request, user,mail_subject,mail_template)
            messages.success(request,"Great! You just created your account! check your mail to activate.")
            return redirect('accounts:signin')
        else:
            print(form.errors)   
    else:    
        form = UserForm()
    return render(request,'accounts/MerchantRegister.html',{'form':form})


def registerSupplier(request):
    if request.user.is_authenticated:
        messages.warning(request,"You are already Logged in !")
        return redirect('accounts:dashboard')
    
    elif request.method == 'POST':
        form = UserForm(request.POST)
        v_form = SupplierForm(request.POST)
        if form.is_valid() and v_form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email,password=password)
            user.role = User.Supplier
            vendor = v_form.save(commit=False)
            vendor.user = user
            vendor_name = v_form.cleaned_data['supplier_name']
            vendor.vendor_slug = slugify(vendor_name)+'-'+str(user.id)
          
            user.set_password(password)
            user.save()
            vendor.save()
            #send verification mail
            mail_subject = 'Please activate your account'
            mail_template = 'accounts/emails/account_verification_email.html'
            send_verification_email(request, user,mail_subject,mail_template)
            
            messages.success(request, 'Your account has been registered sucessfully! Please check your mail to activate and wait for the approval.')
            return redirect('accounts:signin')
        else:
            print(form.errors)
            print(v_form.errors)
    
    else:
        form = UserForm()
        v_form = SupplierForm()
    return render(request,'supplier/supplierRegister.html',{'form':form,'v_form':v_form})


# def signin(request):
#     if request.user.is_authenticated:
#         return redirect('aap:prod')

#     if request.method == 'POST':
#         email = request.POST['e-mail']
#         password = request.POST['password']

#         try:
#             user = User.objects.get(email=email)
#             user_role = user.get_role()
#             print(user,user_role)

#             if user is not None and user_role == 'Merchant':
#                 login(request, user)
#                 return redirect('aap:prod')
        
#             elif user is not None and user_role == 'Supplier':
#                 login(request, user)
#                 return redirect('accounts:dashboard')
#             else:
#                 return redirect('accounts:signin')
#         except User.DoesNotExist:
#             return redirect('accounts:signin')

#     else:
#         return render(request, "accounts/signin.html")

from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.hashers import check_password
from accounts.models import User

# def signin(request):
#     if request.user.is_authenticated:
#         return redirect('aap:prod')

#     if request.method == 'POST':
#         email = request.POST['e-mail']
#         password = request.POST['password']

#         try:
#             user = User.objects.get(email=email)
#             if check_password(password, user.password):  # Compare entered password with stored password
#                 user_role = user.get_role()
#                 print(user,user_role,password)

#                 if user_role == 'Merchant':
#                     login(request, user)
#                     cont={}
#                     cont = products.objects.all()
#                     expiring_products = []
#                     today = timezone.now().date()
#                     for product in products.objects.all():
#                         delta = product.expiry - product.manufacture_date
#                         if delta <= timezone.timedelta(days=30):
#                             expiring_products.append(product)

#                     mail_subject = "Medicines are low! Be Cautious"
#                     mail_template = "emails/expiry_notification.html"

#                     context = {
#                         'expiring_products': expiring_products,
#                         'today': today,
#                         'to_email':email,
#                     }
#                     send_notification(mail_subject,mail_template,context)
#                     return render(request,"products.html",{'cont':cont,'email':email}) 
#                 elif user_role == 'Supplier':
#                     login(request, user)
#                     return render(request,'dash.html',{'email':email})
#             else:
#                 print('passwords not equal.')

#         except User.DoesNotExist:
#             pass

#         return redirect('accounts:signin')

#     else:
#         return render(request, "accounts/signin.html")


def signout(request):
    logout(request)
    return redirect('/')

def activate(request, uidb64, token):
    # Activate the user by setting the is_active status to True
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is now activated.')
        return redirect('accounts:signin')
    else:
        messages.error(request, 'Invalid activation link')
        return redirect('accounts:signin')
    

def signin(request):
    if request.user.is_authenticated:
        return redirect('aap:prod')

    if request.method == 'POST':
        email = request.POST['e-mail']
        password = request.POST['password']

        user = authenticate(request, email=email, password=password)
        if user is not None:
            user_role = user.get_role()
            print(user, user_role)

            if user_role == 'Merchant':
                login(request, user)
                return redirect('aap:prod')
        
            elif user_role == 'Supplier':
                login(request, user)
                return redirect('accounts:dashboard')
        
        return redirect('accounts:signin')

    else:
        return render(request, "accounts/signin.html")
    
def dashboard(request):
    return render(request,'accounts/dash.html')

templates/accounts/MerchantRegister.html
<!DOCTYPE html>
<html>
<head>
    <title>Medico Registration Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
        }
        
        .main-section {
            margin-top: 0;
            padding-top: 60px;
            padding-bottom: 60px;
            margin-bottom: 0;
        }
        
        .user-dashboard {
            background-color: #ffffff;
            border: 1px solid #e0e0e0;
            border-radius: 5px;
            padding: 20px;
        }
        
        .user-holder {
            margin-bottom: 20px;
        }
        
        .text-center {
            text-align: center;
        }
        
        .register-add-restaurant-tab-container {
            list-style-type: none;
            padding: 0;
        }
        
        .field-holder {
            margin-bottom: 20px;
        }
        
        .field-holder label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        
        .field-holder input[type="text"],
        .field-holder input[type="email"],
        .field-holder input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #e0e0e0;
            border-radius: 3px;
        }
        
        .payment-holder {
            text-align: right;
        }
        
        .bgcolor {
            background-color: #4caf50;
            color: #ffffff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
        }
        
        .bgcolor:hover {
            background-color: #45a049;
        }
        
        ul.errorlist {
            color: red;
            list-style-type: none;
            margin: 0;
            padding: 0;
        }
        
        ul.errorlist li {
            margin-bottom: 5px;
        }

        /* Rest of the CSS code */

.navbar {
    background-color: #ffffff;
    height: 60px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0 20px;
    border-bottom: 1px solid #e0e0e0;
}

.logo {
    height: 40px;
}

.navbar-nav {
    list-style-type: none;
    display: flex;
}

.nav-item {
    margin-right: 20px;
}

.nav-link {
    color: #000000;
    text-decoration: none;
}
    </style>
</head>
<body>
    <nav class="navbar">
        <div class="navbar-brand">
            <img src="medico-logo.png" alt="Medico" class="logo">
        </div>
        <ul class="navbar-nav">
            <li class="nav-item"><a href="#" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="{% url 'accounts:signin' %}" class="nav-link">Login/Register</a></li>
        </ul>
    </nav>
    <div class="main-section">
        <div class="page-section nopadding cs-nomargin">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="user-dashboard loader-holder">
                            <div class="user-holder">
                                <h4 class="text-center">WELCOME TO MEDICO</h4>
                                <p class="text-center">Please fill this form to get yourself onboarded.</p>
                                <hr>
                                <!--ALERTS START-->
                                <center>
                                    <ul class="errorlist">
                                        <!-- Error messages will be dynamically added here -->
                                    </ul>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <!-- Load message -->
                                        </div>
                                    </div>
                                </center>
                                <!--ALERTS END-->
                                <div id="restaurant-sets-holder">
                                    <form action="{% url 'accounts:MerchantRegister' %}" class="form-fields-set" method="post">
                                        {% csrf_token %}
                                        <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                            <li>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="row">
                                                            <ul>
                                                                <li>
                                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                                        <div class="field-holder">
                                                                            <label>First name</label>
                                                                            {{form.first_name}}
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                                        <div class="field-holder">
                                                                            <label>Last name</label>
                                                                            {{form.last_name}}
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                                        <div class="field-holder">
                                                                            <label>Email Address</label>
                                                                            {{form.email}}
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                                        <div class="field-holder">
                                                                            <label>Username</label>
                                                                            {{form.username}}
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                                <li>
                                                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                                        <div class="field-holder">
                                                                            <label>Password</label>
                                                                            {{form.password}}
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                                        <div class="field-holder">
                                                                            <label>Confirm Password</label>
                                                                            {{form.confirm_password}}
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="field-holder">
                                                            <div class="payment-holder">
                                                                <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </li>
                                                            </ul>
                                                            </form>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            
                                                            </body>
                                                            </html>

templates/accounts/dash.html
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <style>
    body {
      font-family: Arial, sans-serif;
    }
    
    .dashboard {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      
      grid-gap: 20px;
      padding: 20px;
    }
    
    .card {
      background-color: #f1f1f1;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 2px 5px rgba(0, .8, 0, .8);
    }
    
    .card h2 {
      margin-top: 0;
      font-size: 24px;
      color: #333;
    }

    .card:hover {
      transform: scale(1.05);
    }
    
    .card p {
      margin-bottom: 0;
      color: #666;
    }
     .card:nth-child(1) {
      background-color: #ff8080; /* Light red */
    }
    
    .card:nth-child(2) {
      background-color: #80b3ff; /* Light blue */
    }
    
    .card:nth-child(3) {
      background-color: #b3ffb3; /* Light green */
    }
    
    .card:nth-child(4) {
      background-color: #ffff80; /* Light yellow */
    }

    .topnav{
      background-color:black;
      overflow: hidden;
      display:block;
    }
    .topnav a {
      float: left;
      color: #f2f2f2;
      text-align: center;
      padding:14px 16px;
      text-decoration: none;
      font-size: 17px;
    }
    
    /* Change the color of links on hover */
    .topnav a:hover {
      background-color: #ddd;
      color: black;
    }
    
    /* Add a color to the active/current link */
    .topnav a.active {
      background-color: #04AA6D;
      color: white;
    }
    .topnav P{
      font-family:Apple Chancery, cursive;
      font-size: 18PX;
      color:rgb(18, 235, 224);
    }
  </style>
</head>

<body>
  <div class="topnav">
   
    <a href="{% url 'aap:home' %}">Home</a>
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:signout' %}">Logout</a>
        {% else %}
       < <a href="{% url 'accounts:signin' %}">Login</a>>
        {% endif %}
    </div><br>
    <h3>supplier dashboard</h3>
</div><br>
  <div class="dashboard">
    <div class="card">
      <h2>products</h2>
      <a href="{% url 'aap:prod' %}">product list</a>
    </div>
    <div class="card">
      <h2>Add medicine</h2>
      <a href="{% url 'aap:add_medicine' %}">Add</a>
    </div>
    <div class="card">
      <h2>Orders</h2>
      <p>Total orders: 50</p>
    </div>
    <div class="card">
      <h2>Bill</h2>
      <p>bill</p>
    </div>
  </div>
</body>
</html>

templates/accounts/signin.html
<!DOCTYPE html>
<html>
<head>
  <title>Sign In</title>
  <style>
    /* Center the box */
    html, body {
      height: 100%;
      margin: 0;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    
    /* Styling for the sign-in box */
    .signin-box {
      width: 300px;
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 5px;
      background-color: #f9f9f9;
    }
    
    /* Styling for the form elements */
    .signin-box input[type="email"],
    .signin-box input[type="password"] {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
    }
    
    /* Styling for the sign-in button */
    .signin-box button {
      width: 100%;
      padding: 10px;
      border: none;
      border-radius: 4px;
      background-color: #4CAF50;
      color: #fff;
      font-size: 16px;
      cursor: pointer;
    }
  </style>
</head>
<body>
 <div class="signin-box">
    <h2>Signin</h2>
    <form method="POST" action="{% url 'accounts:signin' %}" >
        {% csrf_token %}
      <input type="email" placehlder="email" name="e-mail" required>
      <input type="password" placeholder="Password" name="password" required>
      <button type="submit">Sign In</button>
    </form>
  </div>
</body>
</html>

templates/accounts/supplierregister.html
<!DOCTYPE html>
<html>
<head>
    <title>Supplier Registration</title>
    <style>
        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
        }
        .form-group {
            margin-bottom: 10px;
        }
        label {
            display: block;
            font-weight: bold;
        }
        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Supplier Registration</h2>
        <form action="url{register_supplier}" method="POST">
            <div class="form-group">
                <label for="company_name">Company Name:</label>
                <input type="text" id="company_name" name="company_name" required>
            </div>
            <div class="form-group">
                <label for="contact_name">Contact Name:</label>
                <input type="text" id="contact_name" name="contact_name" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>